create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  phone text not null,
  area text not null,
  delivery_note text,
  payment_method text not null,
  items jsonb not null,
  total_mru integer not null default 0,
  status text not null default 'new' check (status in ('new','confirmed','preparing','out_for_delivery','completed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
